---
title: "Exploratory Data Analysis - Executive Summary"
format:
  html:
    toc: false
    page-layout: full
---



### Digging deep into data : 

We started things off by searching for missing values in our dataset. Once we found them, we replaced/filled the gaps for key variables with the appropriate info, and we decided to let go of the less important ones. This way, we kept what really mattered and polished up the data for a smoother analysis ride.

Next, we explored how the subreddits are distributed in our dataset, aiming to understand the balance or imbalance. This analysis helps us notice patterns and strategize for further exploration. We observed a notable size difference between the Anime and Movie subreddits compared to the Television subreddit, this could be because of varying popularity, We've decided to focus our attention on the Anime and Movie Reddit data for our further analysis.


### Does Time matter?

We noticed a decline in the number of posts across all subreddits, reaching its peak from January to July 2021. While this period coincided with the pandemic when social media usage was likely high, it doesn't provide significant insights for our analysis.Digging more into the temporal aspects, we explored how post counts vary with time of day, day of the week, and more. Intriguingly, we found no distinct cyclic pattern linked to specific days of the month. This implies that post scores are probably shaped by content availability and user interest, rather than the timing within a month. The consistent engagement in 'anime' and 'television' subreddits suggests an ongoing compelling content, this suggests that capturing user attention isn't strongly correlated with specific times, days, or months.

### How to draw attention?

To keep it short, we compared post length to user engagement across anime, movies, and television subreddits. What we found is that shorter posts, usually under 2000 characters, are more common across all subreddits, especially those with scores under 10,000. Surprisingly, highly engaging posts, often going viral, tend to be concise. So, for content creators and marketers, this insight suggests that brevity might be the key to capturing audience attention in various entertainment categories on Reddit. Addititonally, incorporating media into posts could be an effective strategy for increasing engagement. However, it's important to consider other factors that might influence engagement, such as the time of posting, the specific subreddit community, and the quality of the media content. 

### Top content creators and their engagement with the users

We identified the most engaging authors in each subreddit based on comments, scores, and post counts. Interestingly, in the television subreddit, the author with the highest score is also the one with the most posts. However, in the movie subreddit, this correlation doesn't hold. Notably, in the anime subreddit, bots are the ones ruling both popularity and engagement.

From this we see that each subreddit has unique engagement dynamics. In the TV subreddit, the top author is both prolific and engaging, but this trend is less clear in movies. The prevalence of bots driving engagement in anime challenges the idea that the most engaging content has to be human-created. It emphasizes the importance of understanding each community's dynamics in assessing author roles in content creation and discussions.